### ISSUE TITLE
插件中 Location 302 跳转移至 goblin 发起请求前

### ISSUE THREAD

**Issue by Becivells** [xiecat/goblin#2]

**Comment by Becivells** [comment]
保留响应头中的 Location 新增 Location 字段
```yaml
- url: /config/api
  Match: prefix
  Replace:
    - Request:
        Method:
        - GET
      Response:
        Location: "{{.Static}}api"
```
